### ISSUE TITLE
Show summary of failed tests at bottom of run_apex_tests.py output

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#107]
Currently the full output of run_apex_tests.py with debug log parsing and limit usage output is pretty long.  If you have lots of test methods, it can be hard to find the failing tests.  The script should output a list of failing tests and their stacktraces at the end of its output, after the full method by method output.

**Comment by silne30** [comment]
@jlantz I wouldn't mind working on this if you didn't already start it.

**Comment by jlantz** [comment]
@silne30 Oops, this was already done.  I've been not the greatest at keeping up with CumulusCI's Github Issues :)
