### ISSUE TITLE
updatePackageVersion miscalculates some package upgrades

### ISSUE THREAD

**Issue by almostthor** [SalesforceFoundation/CumulusCI#113]
When attempting to upgrade a package version of 2.6 to 2.10, updatePackageVersion attempts to downgrade the package.

**Comment by e02d96ec16** [comment]
This is also the case when the versions differ on patch version. To paraphrase: 
> When attempting to upgrade a package version of 2.6.1 to 2.6.2, `updatePackageVersion` attempts to downgrade the package.
I replaced the javascript code in my fork, but then again, I changed many other things too, and I've yet to have the time to clean up and prepare a pull request.

**Comment by jlantz** [comment]
Closing as the new `update_dependencies` target in CumulusCI 2 is a completely different implementation that should avoid this issue.
