### ISSUE TITLE
extract_subtype.xsl.rendered: Empty expression!

### ISSUE THREAD

**Issue by powlo** [SalesforceFoundation/CumulusCI#115]
I'm trying to clear out my Dev Org and I was hoping

```
ant uninstallUnpackaged
```

would be the silver bullet I needed.

However on execution I get:

``` log
BUILD FAILED
c:\Users\Paul\workspace\CumulusCI\build\build.xml:497: The following error occurred while executing this line:
c:\Users\Paul\workspace\CumulusCI\build\cumulusci.xml:752: The following error occurred while executing this line:
c:\Users\Paul\workspace\CumulusCI\build\cumulusci.xml:463: The following error occurred while executing this line:
c:\Users\Paul\workspace\CumulusCI\build\cumulusci.xml:483: Fatal error during transformation using c:\Users\Paul\workspace\CumulusCI\build\xsl\extract_subtype.xsl.rendered: Fatal error during transformation using c:\Users\Paul\workspace\CumulusCI\build\xsl\extract_subtype.xsl.rendered: Empty expression!; Line#: 4; Column#: 41
```

Here's extract_subtype.xsl.rendered

``` xsl
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sf="http://soap.sforce.com/2006/04/metadata" xmlns="http://soap.sforce.com/2006/04/metadata"  exclude-result-prefixes="sf">

<xsl:param name="whitelist" select="" />

<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" />

    <xsl:template match="sf:CustomObject">
        <types>
        <xsl:for-each select="sf:businessProcesses">
          <xsl:if test="not(contains($whitelist, concat(',', sf:fullName, ',')))">
            <xsl:if test="not(contains(substring(sf:fullName, 0, string-length(sf:fullName) - 2), '__'))">
              <members><xsl:copy-of select="sf:fullName/text()"/></members>
            </xsl:if>
          </xsl:if>
        </xsl:for-each>
        </types>
    </xsl:template>
</xsl:stylesheet>
```

and properties files in case they can shed any light:

``` properties
#version.properties
required.packages=managed
version.managed=Not Installed
```

``` properties
#cumulusci.properties
cumulusci.package.name=Our Package
cumulusci.package.namespace=ournamespace
cumulusci.package.apiVersion=31.0
cumulusci.package.installClass=
cumulusci.package.uninstallClass=
cumulusci.github.url.raw=https://our-bitbucket-repo
```

Is there a config parameter I'm missing?

Full dump here: http://pastebin.com/LgLzCuvt

**Comment by jlantz** [comment]
I think this is an issue with the Windows Java XSL parser.  I've never seen this issue in OS X or Linux before and it's complaining about this line in the XSL file:
https://github.com/SalesforceFoundation/CumulusCI/blob/master/build/xsl/extract_subtype.xsl#L4

Fortunately, we recently rewrote the package.xml generation logic into Python so we can bypass the Java XSL stuff in Ant altogether with a little bit of configuration.

You'll need to have python and virtualenv installed on your system (see https://virtualenv.pypa.io/en/stable/installation/) to complete the following steps:

- Open a Terminal and change to the directory where CumulusCI 
- Run `virtualenv venv`
- Run `venv\Scripts\activate`
- Run `pip install -r requirements.txt`
- Run `set CUMULUSCI_CLI=True`

If you ever reinitialize your terminal to run Ant commands, use the following steps to enable the virtualenv first:

- Open a Terminal and change to the directory where CumulusCI 
- Run `venv\Scripts\activate`
- Run `set CUMULUSCI_CLI=True`

When you run any Ant targets from CumulusCI that need to generate the package.xml file (i.e., uninstall, updatePackageXml, deployCIPackageOrg), the new python package xml generator will be used.

**Comment by powlo** [comment]
Great! It's unlikely I'll be using CumulusCI in the near future, so feel free to close if you think the issue is resolved.
