### ISSUE TITLE
Avoid setting deploymentStatus for custom metadata types

### ISSUE THREAD

**Issue by ledfordbk** [SalesforceFoundation/CumulusCI#119]
Using custom metadata types and getting an error indicating we need to avoid specifying deploymentStatus for __mdt.object files.

**Comment by jlantz** [comment]
I just checked and I don't think CumulusCI ever touches the deploymentStatus.  However, CumulusCI includes the ant-salesforce.jar file for the Force.com Ant Migration Tool.  I haven't updated it to the latest API version yet which might be the issue.

I don't have a project with Custom Metadata Types yet to play with, but you could test it out locally by just dropping the new ant-salesforce.jar into CumulusCI/build/lib and trying the deployment again.  If that works I'll update it or you can submit a pull request via Github.

**Comment by ledfordbk** [comment]
We are using a pilot in Spring 15 orgs.  I confirmed the 33 jar doesn't work and the 34 jar won't work on Spring orgs.  Our workaround is to move the __mdt.object files from the objects folder to the customMetadata folder until we can use the Summer 15 jar.

**Comment by jlantz** [comment]
Closing old issues to make way for CumulusCI 2 related issues.

CumulusCI 2 does support CustomMetadataTypes in the package.xml generation.
