### ISSUE TITLE
Uninstall fails trying to delete ListView from standard objects 

### ISSUE THREAD

**Issue by michaelhoefer** [SalesforceFoundation/CumulusCI#120]
I'm not sure how CumulusCI is working despite this...perhaps you don't use standard objects? 

We add custom fields to various standard objects.  For example, User.object.  This is what is happening:
1. The sf:retrieve code retrieves all defined list views.
2. The macro to generate destructive changes adds entries for the stock, standard list views, like User.ActiveUsers.
3. Later, the deploy of the destructive changes fails, because it tries to delete all of the standard ListView records.  Fail.

Looks like what we need it to do is add any custom list views, but exclude those standard ones that we don't own and shouldn't touch anyway.  In our case, we don't add any list views to standard objects ourselves...so we could just remove all of them from the downloaded uninstallsrc/object files and be good.  But that isn't a solution for everyone.

**Comment by jlantz** [comment]
Clearing out old issues to get ready for CumulusCI 2 related issues.

For future reference, I believe this was about the uninstallUnmanaged target which is no longer the preferred way to do deletes in CumulusCI.  The preferred method is to use an unmanaged package as a container and then use the `uninstallPackaged` Ant target in old CumulusCI or `cci task run uninstall_packaged`  or `cci task run uninstall_packaged_incremental` in CumulusCI 2.  That will only uninstall the metadata contained in the package and leave all the other unmanaged metadata in place.
