### ISSUE TITLE
Uninstall Fails with Volunteers for Salesforce

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#124]
I've been trying to get Cumulus CI (run by Jenkins) to help build V4SF. I set up a Jenkins server, get Cumulus CI installed, and successfuly deployed to a fresh devorg with the deployCI task.

However, now I'm trying to uninstall and clean the org. I used the `uninstall` task but am running into a huge number of component failures, many of which seem to be related to Campaign.

I did try editing the standard_objects.xml file in /var/lib/jenkins/workspace/CumulusCI/build/ to include Campaign but that didn't help.

My component failures are below. I don't know a lot about ant, so I imagine I'm missing something obvious. Any ideas?

**Comment by cdcarter** [comment]
BUILD FAILED
/var/lib/jenkins/workspace/CumulusCI/build/build.xml:526: 
*********** DEPLOYMENT FAILED ***********
Request ID: 0Af6100000JkbynCAB

All Component Failures:
1.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Shifts__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts.
2.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers_Still_Needed__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed.
3.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Completed_Hours__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours.
4.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Number of Volunteers. This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Number of Volunteers.
5.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Shifts__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts.
6.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers_Still_Needed__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed.
7.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Completed_Hours__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours.
8.  objects/Volunteer_Shift__c.object (Volunteer_Shift__c.Volunteer_Job__c) -- Error: This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Shifts. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: # of Volunteers Still Needed.
9.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Number_of_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Hours__c.Total_Hours_Worked__c. This custom field is referenced elsewhere in salesforce.com. : Volunteer Job Custom Fields: Number of Volunteers.
10.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Shifts__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Shifts.
11.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Number of Volunteers.
12.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Volunteer_Job__c) -- Error: This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Completed Hours. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Volunteers.
13.  objects/Volunteer_Shift__c.object (Volunteer_Shift__c.Desired_Number_of_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Shift__c.Number_of_Volunteers_Still_Needed__c.
14.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Total_Hours_Worked__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Volunteer Job Custom Fields: Number of Completed Hours.
15.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers_Still_Needed__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteers Still Needed.
16.  objects/Volunteer_Shift__c.object (Volunteer_Shift__c.Number_of_Volunteers_Still_Needed__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Volunteer Job Custom Fields: # of Volunteers Still Needed.
17.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Hours_Worked__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Hours__c.Total_Hours_Worked__c.
18.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Campaign__c) -- Error: This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Campaign Custom Fields: Number of Volunteers. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Campaign Custom Fields: Volunteer Completed Hours. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Campaign Custom Fields: Volunteer Jobs. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Campaign Custom Fields: Volunteer Shifts. This object containing this lookup has a summary field in another object. Remove the summary usage and try
19.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Completed_Hours__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Volunteer Completed Hours.
20.  objects/Volunteer_Shift__c.object (Volunteer_Shift__c.Volunteer_Job__c) -- Error: This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Shifts. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: # of Volunteers Still Needed.
21.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Status__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Job__c.Number_of_Volunteers__c. This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Job__c.Number_of_Completed_Hours__c. This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Hours__c.Total_Hours_Worked__c.
22.  objects/Volunteer_Job__c.object (Volunteer_Job__c.Number_of_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Campaign Custom Fields: Number of Volunteers.
23.  objects/Volunteer_Hours__c.object (Volunteer_Hours__c.Volunteer_Job__c) -- Error: This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Completed Hours. This object containing this lookup has a summary field in another object. Remove the summary usage and try again. : Volunteer Job Custom Fields: Number of Volunteers.
24.  objects/Volunteer_Shift__c.object (Volunteer_Shift__c.Total_Volunteers__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - Volunteer_Shift__c.Number_of_Volunteers_Still_Needed__c.
25.  objects/Volunteer_Hours__c.object -- Error: This custom object is used by another feature. Remove the usage and try again. : Custom Formula Field - Volunteer_Job__c.Number_of_Volunteers__c. This custom object is used by another feature. Remove the usage and try again. : Custom Formula Field - Volunteer_Job__c.Number_of_Completed_Hours__c. This custom object is summarized by a field in another object. Remove the usage and try again. : Volunteer Job Custom Fields: Number of Completed Hours. This custom object is summarized by a field in another object. Remove the usage and try again. : Volunteer Job Custom Fields: Number of Volunteers.
26.  objects/Volunteer_Job__c.object -- Error: This custom object is summarized by a field in another object. Remove the usage and try again. : Campaign Custom Fields: Number of Volunteers. This custom object is summarized by a field in another object. Remove the usage and try again. : Campaign Custom Fields: Volunteer Completed Hours. This custom object is summarized by a field in another object. Remove the usage and try again. : Campaign Custom Fields: Volunteer Jobs. This custom object is summarized by a field in another object. Remove the usage and try again. : Campaign Custom Fields: Volunteer Shifts. This custom object is summarized by a field in another object. Remove the usage and try again. : Campaign Custom Fields: Volunteers Still Needed.
27.  objects/Volunteer_Shift__c.object -- Error: This custom object is summarized by a field in another object. Remove the usage and try again. : Volunteer Job Custom Fields: Number of Shifts. This custom object is summarized by a field in another object. Remove the usage and try again. : Volunteer Job Custom Fields: # of Volunteers Still Needed.

*********** DEPLOYMENT FAILED ***********

**Comment by kbromer** [comment]
Looks like uninstall ordering may need some tweaking - maybe a fieldset or something else?

**Comment by cdcarter** [comment]
I've managed to isolate the problem to the five packaged roll-up fields on Campaign. If I delete (and then permanently erase) them before running the `uninstall` target (or `deployCI` for that matter) it succeeds. However, if they are there, the uninstall will fail.

**Comment by cdcarter** [comment]
Weirdly, the destructiveChanges.xml file that is created in the uninstall/ folder does contain the five rollups that are causing the error.

**Comment by cdcarter** [comment]
Closing this out, since it's an issue with the mdAPI and not CumulusCI. I solved it with a preUninstall target.
