### ISSUE TITLE
Remove Custom Field References In Filtered Lookups

### ISSUE THREAD

**Issue by brentfamily1** [SalesforceFoundation/CumulusCI#134]
Scenario:
Given a Custom Field with a Filtered Lookup (fld1) references another Custom Field (fld2),
When the Custom Field referenced in the Filtered Lookup (fld2) needs to be removed,
Then remove the Filtered Lookup reference in the Custom Field with a Filtered Lookup (fld1).

Currently, if a Custom Field is in this scenario and the destroyStaleMetadata target is used then the following error message is received.

> Error: This custom field is referenced elsewhere in salesforce.com. : Filtered Lookup.

Once the Filtered Lookups are removed manually the destroyStaleMetadata target works as expected.

**Comment by jorrit-steporange** [comment]
We're running into the same issue and managed to workaround by creating a predeploy target deploying the fields without the filter. Perhaps it's something you can use in the meantime!

**Comment by brentfamily1** [comment]
@jorrit-steporange could you share your predeploy target here for reference?

**Comment by jorrit-steporange** [comment]
@brentfamily1 I'll try to add it tonight or tomorrow, no problem!

**Comment by jorrit-steporange** [comment]
Hi @brentfamily1, Sorry for my late reply .... 

In my build.xml i've added an extra target
`<target name="preUninstall">
		<echo>Custom preUninstall</echo>
		<sf:deploy username="${sf.username}" password="${sf.password}" `serverurl="${sf.serverurl}"` deployRoot="preuninstall" runAllTests="false" purgeOnDelete="true" maxPoll="${cumulusci.maxPoll.notest}" />
    <echo>Custom preUninstall Done</echo>
</target>`

In my preuninstall folder i've checked the metadata in containing the lookups **without** the filter

Let me know if this helps as a workaround or that you need more information

**Comment by brentfamily1** [comment]
@jorrit-steporange OK, thank you.  Got it.

**Comment by jlantz** [comment]
The Ant targets are now removed from CumulusCI and no longer actively supported. The old Ant target based CumulusCI now lives in the legacy-1.0 branch. I'll try to review and accept pull requests on that branch but will not be actively developing against the Ant version going forward.

All development focus has shifted to CumulusCI 2 which now has feature parity with the Ant based CumulusCI along with far better configurability, access to all Salesforce API's, and encrypted OAuth toolbelt, and a single CLI cci with command help for a much better user experience.
