### ISSUE TITLE
Bug: Lightning Pages error on deployCIPackageOrg

### ISSUE THREAD

**Issue by jtrockstar** [SalesforceFoundation/CumulusCI#136]
With Lightning pages setup for some objects, and retrieved using retrievePackagedToSrc, if you turn around and do a deployCIPackageOrg you get errors during the destroyStaleMetadata (which it shouldn't be trying to destroy at all):

All Component Failures:
1.  flexipages/Opportunity_Record_Page.flexipage -- Error: You can't delete an active Lightning Page. Open the page in Lightning App Builder and click Activation to deactivate it. : Edit page in Lightning App Builder - 0M036000000PGcB.
2.  flexipages/Account_Record_Page.flexipage -- Error: You can't delete an active Lightning Page. Open the page in Lightning App Builder and click Activation to deactivate it. : Edit page in Lightning App Builder - 0M036000000PGJL.

Note: i've seen this in multiple orgs (different packages) 
## 

destroyStaleMetadataManaged:
     [echo] ----------------------------------------------------------------------------
   [delete] Deleting directory /Users/JT/GitHub/SpringCMSDO/uninstallsrc
   [delete] Deleting directory /Users/JT/GitHub/SpringCMSDO/uninstall
    [mkdir] Created dir: /Users/JT/GitHub/SpringCMSDO/uninstallsrc
[sf:retrieve] Request for a retrieve submitted successfully.
[sf:retrieve] Request ID for the current retrieve task: 09S360000083dHeEAI
[sf:retrieve] Waiting for server to finish processing the request...
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: Succeeded
[sf:retrieve] Finished request 09S360000083dHeEAI successfully.
     [xslt] Processing /Users/JT/GitHub/SpringCMSDO/uninstallsrc/package.xml to /Users/JT/GitHub/SpringCMSDO/uninstallsrc/package.xml.members
     [xslt] Loading stylesheet /Users/JT/Github/CumulusCI/build/xsl/diff_package_xml.xsl
     [xslt] Processing /Users/JT/GitHub/SpringCMSDO/src/package.xml to /Users/JT/GitHub/SpringCMSDO/src/package.xml.members
     [xslt] Loading stylesheet /Users/JT/Github/CumulusCI/build/xsl/diff_package_xml.xsl
    [mkdir] Created dir: /Users/JT/GitHub/SpringCMSDO/uninstall
   [delete] Deleting: /Users/JT/GitHub/SpringCMSDO/uninstallsrc/package.xml.members
   [delete] Deleting: /Users/JT/GitHub/SpringCMSDO/src/package.xml.members
     [echo] Deleting metdata with purgeOnDelete=true
[sf:deploy] Request for a deploy submitted successfully.
[sf:deploy] Request ID for the current deploy task: 0Af3600000wvA18CAE
[sf:deploy] Waiting for server to finish processing the request...
[sf:deploy] Request Status: Pending
[sf:deploy] Request Status: Failed

BUILD FAILED
/Users/JT/Github/CumulusCI/build/build.xml:329: The following error occurred while executing this line:
/Users/JT/Github/CumulusCI/build/build.xml:515: 
**********\* DEPLOYMENT FAILED ***********
Request ID: 0Af3600000wvA18CAE

All Component Failures:
1.  flexipages/Opportunity_Record_Page.flexipage -- Error: You can't delete an active Lightning Page. Open the page in Lightning App Builder and click Activation to deactivate it. : Edit page in Lightning App Builder - 0M036000000PGcB.
2.  flexipages/Account_Record_Page.flexipage -- Error: You can't delete an active Lightning Page. Open the page in Lightning App Builder and click Activation to deactivate it. : Edit page in Lightning App Builder - 0M036000000PGJL.

**********\* DEPLOYMENT FAILED ***********

**Comment by jtrockstar** [comment]
Fixed this locally, but it won't let me push / PR so here you go:

In build/cumulusci.xml starting at line 350 add this entry to the case statement:

            <case value="flexipages">
              <property name="typename" value="FlexiPage" />
            </case>

**Comment by jtrockstar** [comment]
@jlantz see above for fix.

**Comment by jlantz** [comment]
@jtrockstar thanks for the info and patch.  We'll get it merged in soon.  I just got done rewriting the package.xml generation logic in Python recently so we'll need to make sure to implement it there too.  @cpolcyn ping me in the morning and we'll work through getting this merged.

**Comment by jlantz** [comment]
The Ant based CumulusCI has now been moved to the `legacy-1.0` branch as master has switched to the new Python based CumulusCI 2 code now.

I made the Flexipage addition in the `legacy-1.0` branch.  Sorry for the the delay in getting that merged.  It's been a crazy last 6 months getting CumulusCI 2 ready.
