### ISSUE TITLE
Field delete order : Could not delete a field on parent with reference from child

### ISSUE THREAD

**Issue by swapnilshrikhande** [SalesforceFoundation/CumulusCI#142]
- Opportunity has two custom Date fields Default_Start__c and Default_End__c
- Opportunity Product has a formula field which references above two fields

When we try to deploy using **deployDO** , when the job first tries to delete Opportunity Fields it cannot delete them, as they are referenced in child object (Opportunity Product) formula field.
Ideally in this case Formula field must be deleted first and then the parent fields.

Currently we need to go into the target org and remove references from formula field pre-deployment.

Any cleaner way to overcome this issue through build configuration?

Log snippet Below

```
[sf:deploy] Component Failures:
[sf:deploy] 
3.  objects/Opportunity.object (Opportunity.Default_Start_Date__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - OpportunityLineItem.Use_Opp_Close_Date__c.

[sf:deploy] Component Failures:
[sf:deploy] 
4.  objects/Opportunity.object (Opportunity.Default_End_Date__c) -- Error: This custom field is referenced elsewhere in salesforce.com. : Custom Formula Field - OpportunityLineItem.Use_Opp_Close_Date__c.

[sf:deploy] ------------------------------------------------------
```

**Comment by cdcarter** [comment]
Hi @swapnilshrikhande - not sure if you're still running into this problem, buuuuut...

So, yea, sometimes this happens. When you have complicated sets of formulas and cross references, it can get messy and the destructive changes aren't always able to execute.

In the past, I've built a very small set of unmanaged metadata that set troublesome formulas to just return an empty string or 0 or another constant, and execute that as a `preUninstall` task. You should be able to do something similar!

**Comment by jlantz** [comment]
Cleaning up older tickets to get ready for handling CumulusCI 2 issues.

The recommendation from @cdcarter is the best bet to get around such constraints.  You can override the build configuration per project to allow you to wire in the specific changes you need to deploy before calling the delete.

**Comment by swapnilshrikhande** [comment]
Thanks @cdcarter, sure @jlantz.
