### ISSUE TITLE
java.lang.OutOfMemoryError during UpdatePackageXml

### ISSUE THREAD

**Issue by celador** [SalesforceFoundation/CumulusCI#150]
I created an empty org.  
I iteratively created lightning components, built the package, and monitored the memory usage.
After I'd created the 29th empty lightning component and ran the Build process, I received the Java OutOfMemoryError.  

During UpdatePackageXml I can see the memory spike to above 4gb and then the Java process dies.
It's as if each AuraDefinitionBundle requires at least 130mb.

**Comment by celador** [comment]
https://github.com/CodeScience/lightning-ci-test is a reference repository

**Comment by jackiedpeacock** [comment]
My team is also having this issue.  We get the OutOfMemory error on the 29th lightning component.

**Comment by celador** [comment]
@jackiedpeacock give the npm package "package-xml" a shot. I made it as a solution to this issue. Let me know how it goes.

**Comment by jackiedpeacock** [comment]
Thx @celador.  I haven't tried it yet - because I've already deleted the additional lightning components so the cumulusci script could continue.   Can you provide more details on what package-xml does?  Does it do everything that the cumulusci script does (i.e. uninstall then install?).

**Comment by celador** [comment]
It only generates the package.xml file. You would need to integrate the
script into whatever build process you have. We use it in tandem with
jsforce-metadata-tools so we can have an all JavaScript build process and
have moved away from Java.

**Comment by jlantz** [comment]
Sorry for the delayed response on this, but there is a way around this error which I wrote after we hit the same error in our packages.  We wrote a new python base package.xml generator which was merged in this PR:
https://github.com/SalesforceFoundation/CumulusCI/pull/135

The new package.xml generator is run when you set the CUMULUSCI_CLI=True environment variable.  Note that this requires a python environment set up.  There are instructions for setting up the python environment here:
https://github.com/SalesforceFoundation/CumulusCI/tree/master/cli#creating-your-virtualenv-venv

You can test by running ant updatePackageXml and you should get a simple output like:
`[exec] Generating src/package.xml from metadata in src`

**Comment by celador** [comment]
@jlantz Cool. I've ported the Python version to a Node.js version... https://www.npmjs.com/package/package-xml

**Comment by jlantz** [comment]
CumulusCI 2 now exclusively uses the new Python based method for generating package.xml which avoids this issue altogether.

The Ant targets are now removed from CumulusCI and no longer actively supported.  The old Ant target based CumulusCI now lives in the `legacy-1.0` branch.  I'll try to review and accept pull requests on that branch but will not be actively developing against the Ant version going forward.

All development focus has shifted to CumulusCI 2 which now has feature parity with the Ant based CumulusCI along with far better configurability, access to all Salesforce API's, and encrypted OAuth toolbelt, and a single CLI `cci` with command help for a much better user experience.
