### ISSUE TITLE
C2 - Remove Org

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#197]
Sometimes I want to disconnect an org that's no longer part of this project.

**Comment by jlantz** [comment]
It'd be a good idea to add cumulusci2 org disconnect <ORG_NAME> to the CLI, but for now you can do this with `rm ~/.cumulusci/RepoName/OrgName.org`

**Comment by davisagli** [comment]
Is this what `cci org remove` is for?

**Comment by cdcarter** [comment]
Yes, yes it is.
