### ISSUE TITLE
C2 - Exit when push is scheduled in the future

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#207]
We use the start_time arg to schedule a push upgrade for a future time, but the CCI session enters a loop polling for status which would continue until the push job completes. Currently I address the issue by ctrl-c killing the process once I'm in the polling loop.

We should address this by detecting that the time is in the future and exit cleanly.

**Comment by Joble** [comment]
What I did before with a bash script I used for CCI1 was if a start time was provided (AKA don't start immediately), it didn't begin monitoring the push.

**Comment by cpolcyn** [comment]
Even when we provide no argument, it uses utcnow() + 15 minutes as the start time, to allow some manual review before pushes start. So even in that case we'd want to exit early instead of waiting for 15+ minutes.
