### ISSUE TITLE
Error more gracefully when org not specified on flow run

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#221]
When you run a flow with no org or default org - it doesn't error until the task fails to construct. 

edit: the original stack trace was misleading.

**Comment by cdcarter** [comment]
Misread the stacktrace, this is not a *requests* issue, but it seems something is weird when unpickling the org config when not a scratch org...

**Comment by cdcarter** [comment]
I'm also hitting it with `cci org list```

**Comment by topherlandry** [comment]
I believe this is fixed now.
https://github.com/SalesforceFoundation/CumulusCI/commit/e05c4769027d3fc40779669bf0447f3485df3fb4
