### ISSUE TITLE
unhandled exception if repo doesn't have a remote named "origin"

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#226]
`EncryptedFileProjectKeychain` depends on `BaseProjectConfig.project_local_dir` which is derived from `BaseProjectConfig.repo_name` which depends on a remote named `origin`.

If the remote named `origin` doesn't exist for the repo, an `org connect` will fail without an explanation of what is going on. 

either project_local_dir should not depend on the remote repo name if it can't be inferred

OR

check_keychain() in cli.py should check for the repo_name and throw a real exception with a useful message.

```
(venv) ➜  caap-batch git:(master) ✗ cci org connect devbox --login-url=https://cdcdev.cs43.my.salesforce.com
Launching web browser for URL https://cdcdev.cs43.my.salesforce.com/services/oauth2/authorize?response_type=code&client_id=3MVG&redirect_uri=http://localhost:8080/callback&scope=web%20full%20refresh_token&prompt=login
Spawning HTTP server at http://localhost:8080/callback with timeout of 300 seconds.
If you are unable to log in to Salesforce you can press ctrl+c to kill the server and return to the command line.
127.0.0.1 - - [03/Feb/2017 11:47:27] "GET /callback?code=KBxT3ZP8HQ_n7GCH8.mptOXKJOCIBfVtyY4eJfJqHvYYJ3w%3D%3D HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/Users/Christian/venv/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/Christian/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/Christian/PycharmProjects/CumulusCI/cumulusci/cli/cli.py", line 387, in org_connect
    config.keychain.set_org(org_name, org_config, global_org)
  File "/Users/Christian/PycharmProjects/CumulusCI/cumulusci/core/keychain.py", line 76, in set_org
    self._set_org(name, org_config, global_org)
  File "/Users/Christian/PycharmProjects/CumulusCI/cumulusci/core/keychain.py", line 213, in _set_org
    self._set_encrypted_org(name, encrypted, global_org)
  File "/Users/Christian/PycharmProjects/CumulusCI/cumulusci/core/keychain.py", line 298, in _set_encrypted_org
    filename = os.path.join(self.project_local_dir, '{}.org'.format(name))
  File "/Users/Christian/venv/bin/../lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by jlantz** [comment]
Yeah, I had a feeling I might have made some incorrect assumptions in writing a rather basic .git file parser.  Thus far I've been able to detect the repo information on my local OS X system and build systems such as CircleCI with the existing code.

The challenge that I'd need to solve to handle this is how do I find the actual repo name from the files in .git in the use case you bring up?  What is the contents of the .git files?  Is there a way to parse a repo name from it?

We also use the .git directory to detect the commit and branch which are used lots of places.  

For mrbelvedereci, I override the .git parsing b/c I'm working with zip downloads of repo commits instead of clones.  I already know the branch and commit so I just pass those in on init of my MrbelvedereProjectYamlConfig subclass.

**Comment by cdcarter** [comment]
Christian Carter [10:26 AM] 
So, git has no real concept of a repo name, just the current working directory. I assume you're using the remote name in the keychain so that two checkouts of the same project could share a keychain?

[10:26]  
just configuring the remote name in the project.yaml and using it for github tasks that way might be cleaner

[10:27]  
this definitely has some weirdness around what config should be aware of vs. what's really in a task run context

[10:28]  
but for current behavior we definitely need our own exception there, I think

Jason Lantz [10:34 AM] 
the other place repo_name is used is in the ~/.cumulusci/* directory structure.  in theory, two checkouts of Cumulus should share the same orgs

[10:34]  
however, I could just use the project: name:  value in cumulusci.yml for that matching

[10:35]  
and I could treat repo_root as wherever we find cumulusci.yml instead of .git

Christian Carter [10:36 AM] 
yea, I think in the yaml (even as an override)

[10:36]  
ultimately you should probably be able to use cci without a git repo

Jason Lantz [10:36 AM] 
yeah

Christian Carter [10:37 AM] 
(even if you can't use the github tasks) (edited)

[10:37]  
so allowing it, even if you lose the ability to share org configs, is worthwhile

Jason Lantz [10:38 AM] 
you could still share org configs that way... the orgs would live under ~/.cumulusci/<project_name_from_cumulusci.yml>

[10:38]  
two directories with the same project name in their yaml would share orgs

[10:38]  
i kinda like that a lot better
