### ISSUE TITLE
Deprecated Account RUS fields can't be deleted due to Field Set availability

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/CumulusCI#228]
The Account fields npe01__FirstDonationDate__c, npe01__LastDonationDate__c, npe01__LifetimeDonationHistory_Amount__c, and npe01__LifetimeDonationHistory_Number__c show a delete option in the field list, but cannot actually be deleted because they are available to the packaged BDE List FS field set.

**Comment by cdcarter** [comment]
Hey @tet3 - I think you want this in the Cumulus repo? Or is this specifically because of how `cci` is generating your destructive changes?

**Comment by tet3** [comment]
Doh! I shouldn't log bugs in the middle of the night while working on something else. Closing,  and I'll repost in the right repo.
