### ISSUE TITLE
Zip file extraction fails due to package name mismatch

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#240]
When extracting a zip file from Contacts & Organizations package using our utility function zip_subfolder() there is a name mismatch because in that project's cumulusci.yml the project name is "Contacts &amp;amp; Organizations". The function checks each file in the zip to see if the filename starts with this path, and in the zip the filenames are under path "Contacts & Organizations". This results in no files extracted, and exception is thrown when the expected package.xml is not found in the extracted files directory.

reproduce:
From inside Contacts & Organizations repo with packaging org already set up: `cci flow run ci_master --org <packaging org>`

**Comment by cpolcyn** [comment]
We could fix this by searching for "&amp;" in the package name and replacing with "&". But first I'd like to understand why it is listed in cumulusci.yml as "&amp;". Seems it should be "&" and escaped as needed for use in URLs.

**Comment by jlantz** [comment]
The formatting difference between the two &'s was lost in translation, but in general I'm not opposed to changing the package name in the cumulusci.yml file for C&O to fix this issue.

However, I have a suspicion there are other tasks that will fail if you change the package name.  We'll need to run the entire build cycle through for the package (ci_feature in scratch org, ci_master and release_beta against packaging, and ci_beta against a scratch org).
