### ISSUE TITLE
Metadata API Version is Hard Coded

### ISSUE THREAD

**Issue by craigargh** [SalesforceFoundation/CumulusCI#272]
The version of the metdata API is hardcoded as 33.0 in the `_build_endpoint_url()` method of the  `BaseMetadataApiCall` class.

```
endpoint = '%s/services/Soap/m/33.0/%s' % (instance_url, org_id)
```

The API version should match the version in the project's settings.

**Comment by cdcarter** [comment]
oh look at that.

**Comment by cpolcyn** [comment]
Also hard-coded in package_zip.py and soap_envelopes.py
