### ISSUE TITLE
cci project info

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#281]
Create a new CLI command that prints out information about how the project has been configured for CumulusCI.  The goal is to provide the user with a quick snapshot of the project's configuration

This would focus on project specific info such as:

* **Config in the project: section**: i.e., api_version overrides, namespace, dependencies, git prefixes
* **Standard task overrides**: All overrides of standard tasks
* **Custom tasks**: All custom tasks specific to the project
* **Standard flow overrides**: All overrides of standard flows
* **Custom flows**: All custom flows specific to the project
* **Services**: All services for the project with their validation status

**Comment by davisagli** [comment]
`cci project info` exists and includes the first bullet point above. For the others, see `cci task list`, `cci flow list` and `cci service list` (though these lists don't indicate which tasks and flows are built in to cci and which are project-specific)
