### ISSUE TITLE
Installation instructions do not match

### ISSUE THREAD

**Issue by naicigam** [SalesforceFoundation/CumulusCI#284]
This is probably an error in my environment, but I could not find the cause.

First, I had to run `pip install --pre cumulusci`, since I could not find a release version.

After that, whenever I try to run `cci` I get 

```
Traceback (most recent call last):
  File "/usr/local/bin/cci", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Jinja2
```

After installing `Jinja2` using `pip install Jinja2`, I get the same error for the `mock` package. 
After that, I get an error for the `cookies` package... so I am probably doing something wrong.

Could you please help me figure out the problem?

Thanks!
Juan M.

**Comment by cdcarter** [comment]
Could you paste in the output of 

```
 ~ > pip search cumulusci -v
```

**Comment by naicigam** [comment]
This is the output:

```
Starting new HTTPS connection (1): pypi.python.org
"POST /pypi HTTP/1.1" 200 None
cumulusci (2.0.0b30)  - Build and release tools for Salesforce developers
```

**Comment by cpolcyn** [comment]
I'm unable to reproduce. Could it be similar to [this](http://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error)? Try

**Comment by juan-cs** [comment]
That was it! After running `easy_install --upgrade pip`, everything worked out.
Thanks!

**Comment by naicigam** [comment]
That was it! After running `easy_install --upgrade pip`, everything worked out.
Thanks!

**Comment by cdcarter** [comment]
@tet3 - you ran into a similar situ at the sprint, want to make sure you know that this probably fixes...
