### ISSUE TITLE
The schedule command should fail if start time in the past is supplied.

### ISSUE THREAD

**Issue by Joble** [SalesforceFoundation/CumulusCI#308]
When scheduling an upgrade with a specified start time, the command should fail if the time provided is in the past.

Why? Because a time in the past will immediately start the upgrade, which wasn't the intent because a time was given. A single misplaced number can lead to a premature upgrade.

**Comment by cpolcyn** [comment]
If we do this, we should add an option to start "now"

**Comment by Joble** [comment]
The way I see it: past time given = failure, future time given = current scheduling behavior, no time given = start ASAP.

**Comment by cpolcyn** [comment]
Agreed except that no time given should stay as it is, where we add 10 or 15 minutes to now so the user can review.

**Comment by Joble** [comment]
Of course. The CCI definition of ASAP. :-)
