### ISSUE TITLE
Execute Anonymous Apex task

### ISSUE THREAD

**Issue by naicigam** [SalesforceFoundation/CumulusCI#314]
I would like to know if there is a task to run Apex code. 
In my case, I need to generate dummy data for the UAT environment.

Thanks!

**Comment by jlantz** [comment]
There should be a more proper task to run anonymous Apex.  We will likely add that soon as we have a need for it too.

If you need something right now, you could build a custom task in your project repo and wire it into the cumulusci.yml file.  If you subclass BaseSalesforceToolingApiTask you'll already get self.tooling which is an authenticated instance of the simple-salesforce API wrapper customized to talk to the Tooling API.

Here's an example of calling an arbitrary url from the Tooling API from our Apex test runner task:
https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/tasks/salesforce.py#L1291-L1295

And here's more on how to use the Tooling API task class:
http://cumulusci.readthedocs.io/en/latest/cookbook.html#query-the-tooling-api

**Comment by juan-cs** [comment]
Thanks! I will give it a try in the next few days and submit a PR.

**Comment by naicigam** [comment]
Thanks! I will give it a try in the next few days and submit a PR.
