### ISSUE TITLE
We had to change packaging Org - failing latest_beta release due to version mismatch

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#323]
Hello,

I apologize for not phrasing the subject more appropriately, please bear with me.

We've used CCI to create several releases, so our github is at tag (lets say) 1.1 Beta 18

We had to change our packaging org since in which those versions don't exist - so the release task fails. 

I have only very basic git knowledge, so i don't know how to properly handle release tags / names.  Nor am I really sure this is where I should tackle the issue. 

Ideally, Id like to seamlessly continue building on the new packaging org but any way to get cci doing releases on the new org would be awesome.

**Comment by jlantz** [comment]
There are 3 possible ways you can deal with this:

1. Delete the old beta tags from Github
2. Change the setting in cumulusci.yml, project -> git -> prefix_beta to something else
3. Manually generate the first 18 beta releases in your current packaging org to get that org's beta count caught up.

Another option would be creating version 1.1 but I presume you don't want to do that yet so I excluded it from the list
