### ISSUE TITLE
--debug doesn't post-mortem a MetadataApiError

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#327]
running a task with --debug that causes a MetadataApiError doesn't drop you into post-mortem for the exception due to the catch at https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/cli/cli.py#L638.

since the metadata client throws this generically, it makes it quite hard to debug the body of your soap request.

also, since we reassign `exception` to a clickexception, --debug-after doesn't even have the exception instance to inspect with.

**Comment by davisagli** [comment]
It looks like this is handled correctly now. Feel free to re-open if I'm wrong.

**Comment by cdcarter** [comment]
I'm not at all confident in the --debug implementation...

**Comment by cdcarter** [comment]
it may be a bigger ticket than just this
