### ISSUE TITLE
Get duration of non-debug Apex tests

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#328]
We currently get duration of Apex test execution only when debug is enabled. This should be possible for non-debug tests too, through the tooling API. Query for the field "RunTime" on the Apex test result.

**Comment by cdcarter** [comment]
due to debug log trimming, we should grab all limits data from the tooling api as well.

**Comment by force2b** [comment]
I don't think the tooling api pulls out SOQL and DML limits. If the debug logs are trimmed due to size what's the best way to pull those out - short of turning off all other debug log settings before executing tests?

**Comment by cdcarter** [comment]
The tooling api produces limits data for test runs, see https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_apextestresultlimits.htm

**Comment by force2b** [comment]
/services/data/v40.0/tooling/query?q=select+id,cpu,dml,dmlrows,soql,queryrows,ApexTestResult.ApexClass.Name,ApexTestResult.MethodName,ApexTestResult.Outcome+from+ApexTestResultLimits+where+ApexTestResultId='07M41000009gaTTEAY'

**Comment by cdcarter** [comment]
```
SELECT Id,ApexClass.Name,
       ApexLogId,TestTimestamp,
       Message,MethodName,Outcome,
       QueueItem.Status,QueueItem.ExtendedStatus,
       RunTime,StackTrace,
       (SELECT 
          Id,Callouts,AsyncCalls,DmlRows,Email,
          LimitContext,LimitExceptions,MobilePush,
          QueryRows,Sosl,Cpu,Dml,Soql 
        FROM ApexTestResults) 
FROM ApexTestResult 
WHERE AsyncApexJobId='{}'
``` to get the whole dataset for a job run.
