### ISSUE TITLE
NameError: global name 'dependency_uninstalled' is not defined

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#334]
the new dependency process fails in some orgs due to uninstall issues

stacktrace: https://gist.github.com/ZergyPoo/95e121a509d40f8a86b11b1eb07a817f
line: https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/tasks/salesforce.py#L597

**Comment by jlantz** [comment]
Fixed in beta39
