### ISSUE TITLE
Missing key "namespace" in task mrbelvedere_publish

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#337]
https://mrbelvedereci.herokuapp.com/builds/3378

**Comment by cpolcyn** [comment]
https://github.com/SalesforceFoundation/CumulusCI/commit/17a4540b02a729002b7f7bb2e59c12011294c76c

The changes here are needed in `cumulusci/tasks/mrbelvedere.py` as well.

**Comment by jlantz** [comment]
We want to abstract out the github dependency resolution logic so it can be reused in both the mrbelvedere.py and in the new meta.xml update task.

**Comment by cpolcyn** [comment]
Fixed in https://github.com/SalesforceFoundation/CumulusCI/commit/8f0d3a5f6eb6c9e7410b8e4fc306b47066d75958
