### ISSUE TITLE
update tutorial with Github setup

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#352]
now that github service is required for dependency management

update the cumulusci public tutorial with the documentation for setting a github personal access token and configuring the github service.

**Comment by Szandor72** [comment]
I could try to squeeze out some hours next week and write something down, if you'd be interested. There a few things on readthedocs that might need an update.

**Comment by davisagli** [comment]
This exists: https://cumulusci.readthedocs.io/en/latest/tutorial.html#github-service
