### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#376]
I've seen this happen a couple times on builds with test failures where something needs to be recompiled. Exception comes from task run_tests_debug. For example see the original build here:
https://mrbelvedereci.herokuapp.com/builds/5237

**Comment by cpolcyn** [comment]
Invalidated by https://github.com/SalesforceFoundation/CumulusCI/pull/382 ?

**Comment by cdcarter** [comment]
This still happens when things need to be recompiled. https://sentry.io/salesforceorg/cumulusci-errors/issues/323508805/

Need to clean up the JUnit writer to be okay with a None stacktrace.
