### ISSUE TITLE
Refresh the access Token 

### ISSUE THREAD

**Issue by shwetasop** [SalesforceFoundation/CumulusCI#384]
How to refresh an access token so that we dont have to always set the output from _cci org info feature_ manually?

There exist a task for SalesforceDX for Cumulusci 2.0.0-beta48 (2017-06-28) named as SFDXOrgTask. Can the same be added so that we dont need Salesforce DX.

**Comment by cpolcyn** [comment]
> How to refresh an access token so that we dont have to always set the output from cci org info feature manually?
What are you using the output from `cci org info` for? Each time this is called it refreshes the OAuth token, for both persistent and scratch orgs.
> There exist a task for SalesforceDX for Cumulusci 2.0.0-beta48 (2017-06-28) named as SFDXOrgTask. Can the same be added so that we dont need Salesforce DX.
The SFDXOrgTask calls out to sfdx in a subprocess. CumulusCI is not a replacement to sfdx, it is complementary.
