### ISSUE TITLE
PR not reflecting updated build status

### ISSUE THREAD

**Issue by ZergyPoo** [SalesforceFoundation/CumulusCI#391]
I had a PR who's build failed, I hit "rebuild" in Mr. Belvedere, and the build finished successfully, but the PR still says checks failed.

PR: https://github.com/SalesforceFoundation/sal/pull/281
Build: https://mrbelvedereci.herokuapp.com/builds/6159

**Comment by cdcarter** [comment]
logged over at MBCI: https://github.com/SalesforceFoundation/mrbelvedereci/issues/74
