### ISSUE TITLE
cci org info and cci org browser should use default org

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#435]
If you have a default org set, you shouldn't need to specify it in the CLI for `cci org info` and `cci org browser`.  What is a bit tricky is that Click requires args to be passed.  Need to investigate how to have an optional arg or something similar.  Perhaps the commands should match `task run` and use `--org <name>` if you want to specify an org other than the default?

**Comment by cdcarter** [comment]
dupe #378

**Comment by cpolcyn** [comment]
related to https://github.com/SalesforceFoundation/CumulusCI/issues/242
