### ISSUE TITLE
Set sfdx alias on created scratch orgs

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#437]
When a scratch org is created via CumulusCI, we should set an sfdx alias on the org using the format `<repo>__<name>`.  A few considerations:

- We need to ensure that `repo` and `name` are valid strings for an sfdx org alias
- Can org aliases be overwritten?  Is there a required no-prompt type option flag needed?
- Do we then switch to using only the alias when getting org info from sfdx?  The advantage would be that the org could be regenerated from the sfdx side under the same alias

**Comment by cdcarter** [comment]
dupe #313 - wanna dd your comment there? or close jason's issue?

**Comment by jlantz** [comment]
Oops, forgot he had filed that one... I'll close this one and leave it as a reference to #313
