### ISSUE TITLE
CCI scratch org on Windows anydbm module missing

### ISSUE THREAD

**Issue by daveb-501commons** [SalesforceFoundation/CumulusCI#491]
I'm watching https://www.youtube.com/watch?v=3NDouZ3-LFE

and mentions after you get cci installed you can do the following
1) git clone https://github.com/SalesforceFoundation/Cumuls
2) cci org scratch dev scratch --default

but I get an error on Windows 10 saying can't find module anydbm.

**Comment by cdcarter** [comment]
@daveb-501commons - can you post the full error message? Thanks.

**Comment by daveb-501commons** [comment]
@cdcarter @jlantz 

Fixed the issue by switching to Python 2.7 instead of Python 3.

Here are the Windows 10 steps related to the Cumulus CI Installation Tutorial.  Let me know if you want me to send up a pull request w/ the Windows Steps included in the tutorial.

http://cumulusci.readthedocs.io/en/latest/tutorial.html#part-1-installing-cumulusci

Windows 10 CumulusCI Installation

**Installation Requirements**

1. Install Git CMD and Git Bash (https://desktop.github.com/)
2. Install Python 2 (Not Python 3) https://www.python.org/downloads/windows/
       Default installed to c:\Python27.  
3. Updated Environment Path to add c:\python27 and c:\python27\Scripts

**Create Virtual Environment**

1. Run Git CMD or Bash as Administrator
2. pip2 install virtualenv
3. mkdir c:\python27\venvs\cumulusci
4. virtualenv –python=c:\python27\python.exe c:\python27\venvs\cumulusci\
5. source c:\python27\venvs\cumulusci\Scripts\activate

**Install CumulusCI**

1. pip install cumulusci

If PyCrypto error then probably need MS C++ 9.0 installed http://aka.ms/vcpython27.  Look at error message should have the link/info.

2. Install MS C++ 9.0 if needed via http://aka.ms/vcpython then repeat step 

the rest of the steps in the tutorial are the same for Windows.

**Comment by cdcarter** [comment]
@daveb-501commons - thank you for your thorough notes. feel free to submit a PR, otherwise we can work these docs in shortly.

we're definitely still a py2.7 app, but working toward py3 compatibility!

**Comment by jlantz** [comment]
The doc updates are now live, closing this issue.

http://cumulusci.readthedocs.io/en/latest/tutorial.html#windows
