### ISSUE TITLE
Package.xml creation: No parser configuration found for subdirectory featureParameters

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#497]
The newly available Feature Management possibilities in Winter18 come with a new metadatatype: featureParameters

This one is not yet recognised by metadata\package.py", line 72, in parse_types

**Comment by Szandor72** [comment]
I changed `metadata_map.yml` and added

```
featureParameters:
    - type: featureParameter
      class: MetadataFilenameParser   
```
No exception occurs anymore and it gives _almost_ the correct result.

Needed Result:
```
    <types>
        <members>debugMode</members>
        <name>FeatureParameterBoolean</name>
    </types>
```

Received result

```
    <types>
        <members>debugMode</members>
        <name>featureParameter</name>
    </types>
```

Folder / Filestructure
```
featureParameters
    - debugMode.featureParameterBoolean
```

File content

```
<?xml version="1.0" encoding="UTF-8"?>
<FeatureParameterBoolean xmlns="http://soap.sforce.com/2006/04/metadata">
    <dataflowDirection>LmoToSubscriber</dataflowDirection>
    <masterLabel>debugMode</masterLabel>
    <value>false</value>
</FeatureParameterBoolean>
```

Possible featureParameters

- FeatureParameterBoolean
- FeatureParameterDate
- FeatureParameterInger

**Comment by jlantz** [comment]
Looks like we need a new parser subclass for a new metadata file naming pattern.  Thanks for the sample content.  I'll see if we can get something into the next release but I'm not sure that'll happen before DF.

**Comment by jlantz** [comment]
OK, there's a chance we don't need a new parser after all.  Can you give this a try?

https://github.com/SalesforceFoundation/CumulusCI/commit/cea636bd22869b5629cfe3ebbfc1cd5886bd581d

**Comment by Szandor72** [comment]
Doesn't work as intended. As before, it doesn't handle the `featureParameters` dir

```
 File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\tasks\metadata\package.py", line 72, in parse_types
    raise MetadataParserMissingError('No parser configuration found for subdirectory %s' % item)
cumulusci.tasks.metadata.package.MetadataParserMissingError: No parser configuration found for subdirectory featureParameters
```

**Comment by jlantz** [comment]
Alright, one more attempt...
https://github.com/SalesforceFoundation/CumulusCI/commit/f36ff470c0e7f4f3574fb87b126c2e22c7f367f7

**Comment by Szandor72** [comment]
Works. Just needs to read `featureParameters`. Thank you very much!

**Comment by jlantz** [comment]
I'll work to get this merged and in the next release too.  Thanks for reporting it and providing enough detail for me to figure it out with having to set up any actual metadata :)
