### ISSUE TITLE
Release Notes parser should warn a release engineer when portions of release notes are dropped

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/CumulusCI#509]
We've missed including some issues in our release notes when the parser dropped them due to lack of a preceding - in markdown to put them in a list. It would be awesome if the parser could warn us when some text below a header hasn't been included.

**Comment by cpolcyn** [comment]
Lacking a `-` doesn't affect whether a line is included, but it can be hard to see when other items do have the bullet marks. Aside from that, notifying others automatically would be possible but would need lots of definition. Currently I generate release notes from my local machine. How would it know who to notify? What conditions would trigger a notification? There's often text that's not included, I think it would get to notification overload pretty quickly.

**Comment by njjc** [comment]
I was just thinking it would notify you while you're generating them that something under a header wasn't included in the notes. I'm not sure exactly why portions of the release notes were omitted, I thought it was the missing ```-``` but I could be wrong. I'll ask in standup tomorrow what the issue was.

**Comment by cpolcyn** [comment]
One thing to keep in mind is that release notes are only generated when the release is created. We can manually regenerate the notes if needed. That means that if PR body changes later, those changes are not reflected in the generated release notes until we manually regenerate.

**Comment by njjc** [comment]
That could totally have been the issue.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL7cAAG" target="_blank">W-022279</a>

**Comment by cpolcyn** [comment]
Closing, invalid
