### ISSUE TITLE
Cannot use default scratch orgs

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/CumulusCI#519]
When attempting to create a scratch org with the name of a predefined default scratch org like "dev", getting an error that it already exists and should be removed. Cannot remove the defaults so the current default names are unusable.

Steps to repo.
cci org scratch dev dev
Error: Org dev already exists.  Use `cci org remove` to delete it.
cci org remove dev
cci org scratch dev dev
Error: Org dev already exists.  Use `cci org remove` to delete it.

**Comment by jlantz** [comment]
After running `cci org remove dev` there's no need to run `cci org scratch dev dev` anymore.  All named scratch configs for each project are automatically created in the keychain.  When removed, a new one is put in its place as `dev` already.  Thus, `cci org scratch dev dev` is doing the right thing in preventing you from overwriting an existing org config.  If you run `cci org list` you'll see the `dev` org there ready to use.

I recently updated the docs on the Org Keychain in `cci` which hopefully can provide more insight into how things work now: http://cumulusci.readthedocs.io/en/latest/features.html#org-keychain

**Comment by jjbennett** [comment]
Thanks! cci org info dev is all I needed to do then since the definition is implied that makes sense.
