### ISSUE TITLE
factor out scratch org password setting

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#522]
so that metaci builds don't have to set a password on scratch org.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL7bAAG" target="_blank">W-022278</a>

**Comment by randi274** [comment]
Adding this would be great. I have to reenter my password into IntelliJ every day and would love it if the password lasted as long as the org.
