### ISSUE TITLE
Bulk Data QueryData task doesn't filter on Record Type

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/CumulusCI#525]
Using SAL as my base repo and adding a block to the mapping file like:
```
Insert Business Organization Accounts:
    sf_object: Account
    table: business_organizations
    fields:
        Id: sf_id
        Name: name
    record_type: Business_Organization
```
The query still looks like ` Submitting query: SELECT Id, Name FROM Account`

**Comment by cdcarter** [comment]
thanks @davidjray, i can confirm we don't have RT filtering on the query task currently. shouldn't be too hard to add though.

are there additional parameters on the query you wish to be able to specify?

**Comment by davidjray** [comment]
I can't think of anything off the top of my head @cdcarter. However a cool feature would be a "Where" option, then the sub nodes could be name/value pairs that dynamically build the where statements... That's all I got ;)
