### ISSUE TITLE
Better error reporting when build fails due to missing environment variables

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/CumulusCI#55]
I believe it was because I didn't have all the necessary environment variables set up that the build failed. The log was not very explanatory:

![screen shot 2014-10-10 at 10 45 46 am](https://cloud.githubusercontent.com/assets/1894238/4595027/f7277c62-5094-11e4-9438-d306d50cd901.png)

**Comment by jlantz** [comment]
CumulusCI 2 now throws *hopefully* more meaningful Python exceptions with more information about what happened.
