### ISSUE TITLE
Allow MetaCI to provide Quip notifications on error/failure

### ISSUE THREAD

**Issue by dylanhansen** [SalesforceFoundation/CumulusCI#564]
I'd love to be able to have a way for CumulusCI (MetaCI?) to post error / failure notifications for a given plan to a Quip chat room.

This will allow for us to gain visibility of key failures that will block releases.

Ideally this would function similar to GitHub's Quip integration, in which you can select a repository and a Quip chat room and choose level of severity of when to post.

**Comment by cpolcyn** [comment]
Moving issue to MetaCI
