### ISSUE TITLE
CumulusCI does not support multiple connected apps for Codeship jobs

### ISSUE THREAD

**Issue by swagattalsania** [SalesforceFoundation/CumulusCI#633]
Hi team.
I am facing an issue where CumulusCI commands fail when you have commands spanning multiple orgs. Consider the following scenario that I have:

1. Developers develop in their respective development orgs/branches
2. They raise PRs for the main development org/branch
3. As soon as the PR is merged into the development branch, a Codeship job kicks in, deploys the code to the org and runs all the tests in that org
4. Once that job is successful, we raise another PR for the master branch which points to the main packaging org
5. As soon as the PR is merged into the master branch, a job kicks in and deploys the code to the packaging org and runs all the tests in that main packaging org

Now to support the above scenario, I have configured below mentioned environment variables in Codeship:

**CUMULUSCI_KEY**
**CUMULUSCI_KEYCHAIN_CLASS**
**CUMULUSCI_CONNECTED_APP**
**CUMULUSCI_ORG_dev**
**CUMULUSCI_ORG_packaging**

The commands run only for the org that is configured in the connected app environment variable and fails with the error **"expired access/refresh token"** for other orgs.

**Comment by jlantz** [comment]
How did you get the values for the CUMULUSCI_CONNECTED_APP and CUMULUSCI_ORG_* env vars?

All 3 values should be in json format.  There is only one connected app used by cci when running cci org connect <org_name>.  That same connected app is used for all the orgs.  To get the org json to load, use cci org info <org_name> --json

**Comment by swagattalsania** [comment]
Hi Jason,
To get the value of CUMULUSCI_CONNECTED_APP I used the command **cci org connected_app** while I used **cci org info <org_name> --json** command to get the values of CUMULUSCI_ORG_* env vars.

When I ran the **cci org connected_app** command, it gave me the JSON for the last org that I connected using the **cci org config_connected_app** command. The Codeship commands only work for this org. If I use the config_connected_app command for the other org and then change the env variable to use the latest JSON from **cci org connected_app** command, it will work for the later org and will fail for the previous one.

This does not serve my purpose of using both the apps in the same job.

**Comment by jlantz** [comment]
I think the problem is that you used two different connected apps, one for each of the orgs you connected.  CumulusCI only uses one connected app for connections to all orgs.  So, if you created a connected app, ran `cci org config_connected_app` then ran `cci org connect dev` and then repeated the process for packaging, you would only be able to connect to the packaging org and not dev.

I think you could resolve the current situation by using `cci org remove <org_name>` on the org that's not working and running `cci org connect <org_name>` again to reconnect to it using the connected app currently configured in CumulusCI.

**Comment by swagattalsania** [comment]
It worked.

So we do not need connected apps in each org for adding it to CumulusCI. I think that is what I was missing. Thanks a lot for the info Jason.
