### ISSUE TITLE
CI jobs

### ISSUE THREAD

**Issue by swagattalsania** [SalesforceFoundation/CumulusCI#634]
Hello team,
I have a question.

If I have multiple tasks configured in my CI software and if one the tasks fail, will everything be rolled back?

Example, I have a CI job in Codeship that has 2 tasks viz. 1) to deploy the code from the repository to the org and 2) run all tests.

Now if 2nd task fails, will it roll back the deployment as well or that is not the case?

**Comment by cdcarter** [comment]
no, there's no rollback in our flows. salesforce doesn't have a native rollback function for metadata like that, so you'd need to track what was in the org before you attempted a deploy. this is fairly complex, unfortunately.

**Comment by swagattalsania** [comment]
Thought so. Just wanted to confirm. :)

Thanks Christian!
