### ISSUE TITLE
Windows 10 - Error: No such command "config_connected_app".

### ISSUE THREAD

**Issue by tomharney** [SalesforceFoundation/CumulusCI#660]
cci org config_connected_app
Usage: cci org [OPTIONS] COMMAND [ARGS]...

Error: No such command "config_connected_app".

cumulusci (2.0.0)
Python version: 2.7.14
OS: Windows 10

Pip module list:
arrow (0.12.1)
asn1crypto (0.24.0)
backports.functools-lru-cache (1.5)
certifi (2018.4.16)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
colorama (0.3.9)
coloredlogs (9.3.1)
contextlib2 (0.5.5)
cookies (2.2.1)
cryptography (2.2.2)
cumulusci (2.0.0)
docutils (0.14)
enum34 (1.1.6)
funcsigs (1.0.2)
future (0.16.0)
github3.py (0.9.6)
HiYaPyCo (0.4.11)
humanfriendly (4.12.1)
idna (2.6)
ipaddress (1.0.22)
Jinja2 (2.10)
lxml (4.2.1)
MarkupSafe (1.0)
mock (2.0.0)
monotonic (1.5)
pbr (4.0.4)
pip (9.0.1)
plaintable (0.1.1)
pycparser (2.18)
pycrypto (2.6.1)
PyGithub (1.39)
PyJWT (1.6.4)
pyOpenSSL (18.0.0)
pyreadline (2.1)
python-dateutil (2.7.3)
pytz (2018.4)
PyYAML (3.12)
raven (6.7.0)
requests (2.18.4)
responses (0.9.0)
robotframework (3.0.4)
robotframework-seleniumlibrary (3.1.1)
rst2ansi (0.1.5)
salesforce-bulk (2.0.0)
sarge (0.1.4)
selenium (3.11.0)
setuptools (28.8.0)
simple-salesforce (0.74.2)
six (1.11.0)
SQLAlchemy (1.2.7)
unicodecsv (0.14.1)
uritemplate (3.0.0)
uritemplate.py (3.0.2)
urllib3 (1.22)
virtualenv (16.0.0)
xmltodict (0.10.2)

**Comment by cdcarter** [comment]
Hi @tomharney - we need to update our docs for the latest release. You can now use `cci service connect connected_app` instead of the command you were trying.
