### ISSUE TITLE
Cannot create scratch org through cci org info dev 

### ISSUE THREAD

**Issue by mishraankit191** [SalesforceFoundation/CumulusCI#667]
I am getting the following error while creating a scratch through the projects keychain using dev as my config_name. 
when I copy the sfdx command out of the cci error pasted below:

> sfdx force:org:create -f orgs/dev.json -n --durationdays 7 -a "my_repo__dev"

I can see that scratch org on my sfdx force:org:list command; not sure why cci can't link the request by itself. 

> (cci) c:\GitHub\my_repo>cci org info dev
> [32m2018-06-13 14:18:54:[0m Creating scratch org with command sfdx force:org:create -f orgs/dev.json -n --durationdays 7 -a "my_repo__dev"
> 'C:\Users\FirstName' is not recognized as an internal or external command,
> operable program or batch file.
> Error: ScratchOrgException: Failed to create scratch org:

**Comment by jstvz** [comment]
Hi @mishraankit191! We've recently pushed some updates that I think resolve this issue. Is the latest version of `cci` still producing this error?

**Comment by mishraankit191** [comment]
hi @jstvz, the last three updates resolved the issue, I'm now able to create/renew scratch orgs directly from cci keychain, thanks!

**Comment by jstvz** [comment]
Thanks!
