### ISSUE TITLE
Error in InstallPackageVersion.py in Python 3

### ISSUE THREAD

**Issue by wlonk** [SalesforceFoundation/CumulusCI#729]
In `cumulusci/tasks/salesforce/InstallPackageVersion.py:58` in the branch `feature/python3`, there's a reference to a variable `message` that is not defined in that method.

**Comment by davisagli** [comment]
Thanks, I was moving too fast when converting `e.message` to `str(e)` and apparently we need more coverage here... Just pushed a fix.
