### ISSUE TITLE
Queue concurrent feature branch builds at Codeship

### ISSUE THREAD

**Issue by almostthor** [SalesforceFoundation/CumulusCI#73]
How can we handle the following scenario when an organization has >1 concurrent build for their Codeship account:
1. User A pushes feature/User-A-Code branch on repo my_package
2. Codeship starts build of feature/User-A-Code to the my_package.feature org
3. User B pushes feature/User-B-Code branch on repo my_package
4. Codeship starts a concurrent build of feature/User-B-Code to the my_package.feature org
5. feature/User-B-Code build fails due to the my_package.feature org is still deploying feature/User-A-Code branch

**Comment by freshkurt** [comment]
@almostthor just stumbled upon this - did you mean something like this: https://blog.codeship.com/flexible-deployment-pipelines/ ?

**Comment by jlantz** [comment]
Cleaning up as part of clearing out old issues.

CumulusCI does not intend to solve any concurrency challenges.  The purpose of CumulusCI is to run a single build operation against a single org.  The CI application is what should be responsible for handling concurrency of builds.

If anyone's interested, CumulusCI has a new related project, [mrbelvedereci](https://github.com/SalesforceFoundation/mrbelvedereci), which we're now using for production builds (as of a week ago).  It is a Salesforce specific CI app and thus is able to properly handle concurrency by queuing builds against persistent orgs and running builds against scratch orgs concurrently.  Our instance is at https://mrbelvedereci.herokuapp.com for reference.
