### ISSUE TITLE
Specify in environment variable the directory for Ant to use to create temp files

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/CumulusCI#75]
Ant generates a lot of temporary files that it needs for processing. We could let the user define where to create them, so no dev mistakenly commits one of them to the repo if he sees it inside the project.

Low priority, since it's unlikely this happens.

**Comment by jlantz** [comment]
CumulusCI 2 now uses Python's tempfile module to generate temporary directories and temporary files and deletes them when done.
