### ISSUE TITLE
Can we use it with bitbucket ?

### ISSUE THREAD

**Issue by siddharatha** [SalesforceFoundation/CumulusCI#76]
Our company has a bitbucket license , can I use this with bitbucket instead of github ? #Question

**Comment by briandunz** [comment]
@jlantz My company uses BitBucket as well.  We are looking to automate the build process now that we have refactored our codebase to allow for deploying to clean DE orgs.  I'm willing to help out with building the BitBucket integration if you can lend some guidance.

**Comment by silne30** [comment]
@jlantz I would be willing to take a stab at this if this is still needed.

**Comment by jlantz** [comment]
I'd love to see integration with Bitbucket/Stash as we've had a few ISVs
express interest in that integration.  We will continue to use Github at
the Foundation because we have so many open source projects, but I think
this would be a great integration to make available to the community.

**Comment by maheshsurya26** [comment]
Hey @jlantz , we too are planning to move to Bitbucket from Github. When can we expect  this enhancement.

**Comment by jlantz** [comment]
I don't have any current plans to build an integration with Bitbucket as we
don't have a need for it for our projects which are hosted on Github.
However, that's why CumulusCI is open source :)  I'd be happy to work with
someone who is a Bitbucket user to help implement Bitbucket support if
you're interested.

**Comment by Dharmesh3094** [comment]
@jlantz  : Any update on enhancement of integration with Bitbucket as our company is using Bitbucket for SCM and I think that Cumulus is great tool for managing & automating scratch orgs over writing shell scripts . 
It would be apricated if you can help on  Cumulus_CI & Bitbucket integration

**Comment by jlantz** [comment]
@Dharmesh3094 We have no active plans at this point in time to add support for other SCM systems.  It's an idea we've considered and have a decent understanding of how we'd do it though it's a fair amount of engineering to do it right.  That said, much of CumulusCI can be used against any git repository.  The areas that are tied to GitHub are dependency resolution against other CumulusCI repositories and some of the SCM automation tasks, those that start with `github_`.  It is possible to use CumulusCI and not use those features.
